#!/usr/bin/env bash
# Write .env, Caddyfile, and LibreChat configuration files.
# shellcheck shell=bash source-path=SCRIPTDIR
set -euo pipefail

source "$(dirname "${BASH_SOURCE[0]}")/lib/colors.sh"

backup_file() {
    local file="$1"
    if [[ -f "$file" ]]; then
        cp "$file" "${file}.bak.$(date +%Y%m%d-%H%M%S)"
    fi
}

write_env() {
    backup_file ".env"
    cat > ".env" <<CONFIGEOF
# Graph RAG Assistant - Environment Configuration
# Generated by scripts/install.sh on $(date)

OPENAI_API_KEY=${OPENAI_API_KEY}
OPENAI_MODEL=gpt-5.4
ROUTER_MODEL=gpt-5.4-mini
CYPHER_MODEL=gpt-5.4-mini
CONTEXTUAL_RETRIEVAL_MODEL=gpt-5.4-nano
COMMUNITY_SUMMARY_MODEL=gpt-5.4-nano
EMBEDDING_MODEL=text-embedding-3-large
EMBEDDING_DIMENSIONS=3072
EMBEDDING_BATCH_SIZE=96
LLM_TEMPERATURE=0.1

ENABLE_OCR=false
MIN_TEXT_CHARS_FOR_OCR=100

QDRANT_ENABLE_NATIVE_SPARSE=true
QDRANT_DENSE_VECTOR_NAME=dense
QDRANT_SPARSE_VECTOR_NAME=text_sparse
QDRANT_UPSERT_BATCH_SIZE=500

RETRIEVAL_OVERSAMPLING_FACTOR=3
RETRIEVAL_LEXICAL_WEIGHT=0.15
RETRIEVAL_SCORE_THRESHOLD=0.25
ENABLE_RERANKER=true
RERANKER_MODEL=cross-encoder/mmarco-mMiniLMv2-L12-H384-v1

ENABLE_RICH_CONTEXTUAL_RETRIEVAL=true
CONTEXTUAL_RETRIEVAL_MAX_DOC_CHARS=12000
CONTEXTUAL_RETRIEVAL_CONCURRENCY=5

ENABLE_GLINER=true
GLINER_MODEL=gliner-community/gliner_small-v2.5
GLINER_LABELS=Persona,Organizzazione,Luogo,Prodotto,Concetto,Regola,Requisito,Rischio,Data,Numero,Sistema
GLINER_THRESHOLD=0.5

AGENT_MAX_ITERATIONS=3
AGENT_CYPHER_MAX_RETRIES=1
AGENT_MAX_GRAPH_FACTS=20
AGENT_MAX_COMMUNITY_SUMMARIES=5
COMMUNITY_DETECTION_ALGORITHM=louvain
COMMUNITY_DETECTION_RESOLUTION=1.0
COMMUNITY_SUMMARY_MAX_ENTITIES=50

SECRET_KEY=${SECRET_KEY}
ACCESS_TOKEN_EXPIRE_MINUTES=60
AUTO_CREATE_TABLES=true

POSTGRES_USER=postgres
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
POSTGRES_DB=graph_rag_assistant

NEO4J_PASSWORD=${NEO4J_PASSWORD}

MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
MINIO_SECRET_KEY=${MINIO_SECRET_KEY}

CELERY_BROKER_URL=redis://redis:6379/0
CELERY_RESULT_BACKEND=redis://redis:6379/0

MCP_API_KEY=${MCP_API_KEY}

# Domains configured during setup
DOMAIN_ROOT=${DOMAIN_ROOT}
DOMAIN_ADMIN=${DOMAIN_ADMIN}
DOMAIN_API=${DOMAIN_API}
DOMAIN_CHAT=${DOMAIN_CHAT}
DOMAIN_CHAT_ADMIN=${DOMAIN_CHAT_ADMIN}
DOMAIN_MCP=${DOMAIN_MCP}

JWT_SECRET=${JWT_SECRET}
JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}
CREDS_KEY=${CREDS_KEY}
CREDS_IV=${CREDS_IV}

LIBRECHAT_BACKEND_API_KEY=${LIBRECHAT_BACKEND_API_KEY}
MEILI_MASTER_KEY=${MEILI_MASTER_KEY}

# Network binding
# IP address on which Docker binds the public ports exposed by Caddy (80/443).
HOST_IP=${HOST_IP:-0.0.0.0}
CONFIGEOF
}

write_caddyfile() {
    backup_file "Caddyfile"
    cat > "Caddyfile" <<CONFIGEOF
${DOMAIN_ADMIN} {
    reverse_proxy admin:80
}

${DOMAIN_API} {
    reverse_proxy backend:8000
}

${DOMAIN_CHAT} {
    reverse_proxy librechat:3080
}

${DOMAIN_CHAT_ADMIN} {
    reverse_proxy librechat-admin:3000
}

${DOMAIN_MCP} {
    @authorized header X-MCP-API-Key {\$MCP_API_KEY}
    handle @authorized {
        reverse_proxy mcp:8000
    }
    respond 401
}

${DOMAIN_ROOT} {
    redir https://${DOMAIN_ADMIN}{uri}
}
CONFIGEOF
}

write_librechat_config() {
    backup_file "librechat/librechat.yaml"
    cat > "librechat/librechat.yaml" <<CONFIGEOF
# LibreChat configuration for Graph RAG Assistant
version: 1.3.13

cache: true

mcpSettings:
  allowedAddresses:
    - "mcp:8000"

endpoints:
  custom:
    - name: "Graph RAG Assistant"
      apiKey: "${LIBRECHAT_BACKEND_API_KEY}"
      baseURL: "http://backend:8000/api/v1"
      models:
        default: ["gpt-5.4"]
        fetch: false
      titleConvo: false
      titleModel: "gpt-4o-mini"
      summarize: false
      summarizeModel: "gpt-4o-mini"
      forcePrompt: false
      modelDisplayLabel: "Graph RAG Assistant"
      dropParams: ["user"]

mcpServers:
  graph-rag-assistant:
    type: sse
    url: http://mcp:8000/sse
    timeout: 60000
    initTimeout: 30000
    serverInstructions: |
      Usa questi strumenti quando l'utente chiede informazioni presenti nella knowledge base.
      Preferisci search_knowledge_base quando servono fonti o controllo sui passaggi recuperati.
      Usa answer_knowledge_base quando l'utente vuole direttamente una risposta sintetica con citazioni.
CONFIGEOF
}

write_librechat_env() {
    backup_file "librechat/librechat.env"
    cat > "librechat/librechat.env" <<CONFIGEOF
HOST=0.0.0.0
PORT=3080
MONGO_URI=mongodb://mongo:27017/LibreChat
MEILI_HOST=http://meilisearch:7700
MEILI_MASTER_KEY=${MEILI_MASTER_KEY}
OPENAI_API_KEY=user_provided
JWT_SECRET=${JWT_SECRET}
JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}
CREDS_KEY=${CREDS_KEY}
CREDS_IV=${CREDS_IV}

DOMAIN_CLIENT=https://${DOMAIN_CHAT}
DOMAIN_SERVER=https://${DOMAIN_CHAT}
ADMIN_PANEL_URL=https://${DOMAIN_CHAT_ADMIN}/admin

ALLOW_REGISTRATION=false
ALLOW_PASSWORD_RESET=true
ALLOW_UNVERIFIED_EMAIL_LOGIN=true

EMAIL_FROM=${EMAIL_FROM}
EMAIL_FROM_NAME=${EMAIL_FROM_NAME}
EMAIL_HOST=smtp.resend.com
EMAIL_PORT=587
EMAIL_ENCRYPTION=starttls
EMAIL_USERNAME=resend
EMAIL_PASSWORD=${RESEND_API_KEY}
CONFIGEOF
}

write_librechat_admin_env() {
    backup_file "librechat/admin.env"
    cat > "librechat/admin.env" <<CONFIGEOF
SESSION_SECRET=${SESSION_SECRET}
VITE_API_BASE_URL=https://${DOMAIN_CHAT}
API_SERVER_URL=http://librechat:3080
PORT=3000
CONFIGEOF
}

run_config() {
    if [[ ! -f "docker-compose.yml" ]]; then
        log_error "Esegui questo script dalla root del progetto Graph RAG Assistant."
        exit 1
    fi
    log_step "50" "Scrittura file di configurazione"
    mkdir -p librechat
    write_env
    write_caddyfile
    write_librechat_config
    write_librechat_env
    write_librechat_admin_env
    chmod 600 ".env" "librechat/librechat.env" "librechat/admin.env"
    log_success "File di configurazione scritti."
}
